name: Production Build & Deploy

on:
  push:
    branches:
    - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm run build -- --prod
    - uses: w9jds/firebase-action@master
      with:
        args: deploy -P production --only hosting,storage,firestore:rules,functions
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

